version: '3.7'

# Please replace value depending on your project
## Environment variables for workspace
x-app-working-dir: &APP_WORKING_DIR
  "/home/nuxtjs-sample-template"
x-app-volumes: &APP_VOLUMES
  - ".:/home/nuxtjs-sample-template"
x-app-ports: &APP_PORTS
  - 3000:3000
x-app-environment: &APP_ENVIRONMENT
  - HOST=0.0.0.0
  - PORT=3000

services:
  workspace:
    build:
      context: ./docker/workspace
    container_name: template-workspace
    volumes: *APP_VOLUMES
    working_dir: *APP_WORKING_DIR
    ports: *APP_PORTS
    tty: true
    environment: *APP_ENVIRONMENT
