version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '13.13.0-buster'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test

workflows:
  build-and-test:
    jobs:
      - build-and-test
